name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
        
  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: download file
      uses: actions/download-artifact@v4
      with:
        path: /root/
    - name: read the file
      run: cat /root/hello.txt

